=== indicoder/intense80/WebContent/courses/all-courses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.intense80.com"
xmlns="http://www.intense80.com" elementFormDefault="qualified" attributeFormDefault="unqualified">
          <!-- XML Schema Generated from XML Document on Sat Nov 19 2016 13:29:29 GMT+0530 (IST) -->
          <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
       <xs:element name="courses">
          <xs:complexType>
           <xs:sequence>
            <xs:element name="course" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                         <xs:element name="course-name" type="xs:string"></xs:element>
                         <xs:element name="short-description" type="xs:string"></xs:element>
                         <xs:element name="duration" type="xs:string"></xs:element>
                         <xs:element name="start-date" type="xs:string"></xs:element>
                         <xs:element name="coursefee" type="xs:string"></xs:element>
                         <xs:element name="classroom-location" type="xs:string"></xs:element>
                         <xs:element name="placement-support-available" type="xs:string"></xs:element>
                         <xs:element name="clickthrough-to-details" type="xs:string"></xs:element>
                         <xs:element name="long-description" type="xs:string"></xs:element>
                         <xs:element name="pre-registration-allowed" type="xs:string"></xs:element>
                         <xs:element name="early-registration-fee"></xs:element>
                         <xs:element name="tags">
                            <xs:complexType>
                                   <xs:sequence>
                                          <xs:element name="tag" maxOccurs="unbounded" type="xs:string"></xs:element>
                                      </xs:sequence>
                               </xs:complexType>
                            </xs:element>
                         <xs:element name="what-it-includes">
                            <xs:complexType>
                               <xs:sequence>
                                  <xs:element name="core" type="xs:string"></xs:element>
                                  <xs:element name="optional" type="xs:string"></xs:element>
                                  <xs:element name="others" maxOccurs="unbounded" type="xs:string"></xs:element>
                                 </xs:sequence>
                               </xs:complexType>
                            </xs:element>
                         <xs:element name="detailed-topics">
                            <xs:complexType>
                              <xs:sequence>
                                     <xs:element name="topic" maxOccurs="unbounded" type="xs:string"></xs:element>
                                 </xs:sequence>
                               </xs:complexType>
                            </xs:element>
                         <xs:element name="other-imp-details">
                                <xs:complexType>
                                       <xs:sequence>
                                              <xs:element name="student-profiles">
                                                     <xs:complexType>
                                                            <xs:sequence>
                                                                   <xs:element name="profile" maxOccurs="unbounded" type="xs:string"></xs:element>
                                                               </xs:sequence>
                                                        </xs:complexType>
                                                 </xs:element>
                                              <xs:element name="placement-features">
                                                     <xs:complexType>
                                                            <xs:sequence>
                                                                   <xs:element name="feature" maxOccurs="unbounded" type="xs:string"></xs:element>
                                                               </xs:sequence>
                                                        </xs:complexType>
                                                 </xs:element>
                                          </xs:sequence>
                                   </xs:complexType>
                            </xs:element>
                         <xs:element name="trainer">
                                <xs:complexType>
                                       <xs:sequence>
                                              <xs:element name="name" type="xs:string"></xs:element>
                                              <xs:element name="description" type="xs:string"></xs:element>
                                          </xs:sequence>
                                   </xs:complexType>
                            </xs:element>
                         <xs:element name="faqs">
                                <xs:complexType>
                                       <xs:sequence>
                                              <xs:element name="faq" maxOccurs="unbounded">
                                                     <xs:complexType>
                                                            <xs:sequence>
                                                                   <xs:element name="question" type="xs:string"></xs:element>
                                                                   <xs:element name="answer" type="xs:string"></xs:element>
                                                               </xs:sequence>
                                                        </xs:complexType>
                                                 </xs:element>
                                          </xs:sequence>
                                   </xs:complexType>
                            </xs:element>
                         <xs:element name="course-outline"></xs:element>
                     </xs:sequence>
                  </xs:complexType>
               </xs:element>
            </xs:sequence>
         </xs:complexType>
      </xs:element>
   </xs:schema>

=== indicoder/intense80/WebContent/courses/all-courses.xml
<?xml version="1.0" encoding="UTF-8"?>

<courses xmlns="http://www.intense80.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.intense80.com all-courses.xsd">
	<course>
		<course-name>CompleteJava</course-name>
		<short-description>Complete Java Development (Core + Advanced)</short-description>
		<duration>2.5 Months (80 Days)</duration>
		<start-date>25 Nov 2016</start-date>
		<coursefee>16,000</coursefee>
		<classroom-location>Marathahalli, Bangalore</classroom-location>
		<placement-support-available>Y</placement-support-available>
		<clickthrough-to-details>Y</clickthrough-to-details>
		<long-description>Our innovative courses are designed to help students, fresh/recent graduates get a software job by building pro. Our innovative courses are designed to help students, fresh/recent graduates get a software job by building pro.</long-description>
		<pre-registration-allowed>N</pre-registration-allowed>
		<early-registration-fee></early-registration-fee>
		<tags>
			<tag>Placement Focussed</tag>
			<tag>Beginner Level</tag>
			<tag>Mentor Guidance</tag>
		</tags>
		<what-it-includes>
			<core>Java (Core + Advanced), SQL &amp; Web (HTML, CSS, JavaScript)</core>
			<optional>Spring, Hibernate, AngularJS</optional>
			<others>5 Foundation projects + 2 Major projects</others>
			<others>Assignment, Quizzes, Group work &amp; Reviews</others>
			<others>1:1 Mentoring &amp; Doubt Clearing Sessions</others>	
			<others>6 Month access to online discussion and help forum</others>		
		</what-it-includes>
		<detailed-topics>
			<topic>Core Java</topic>
			<topic>Advanced Java (Servlet, JSP)</topic>
			<topic>SQL &amp; JDBC</topic>
			<topic>Web (HTML, CSS, JavaScript, JQuery)</topic>
			<topic>Data Structure &amp; Algorithm (Optional)</topic>
			<topic>Spring &amp; Hibernate (Optional)</topic>
			<topic>AngularJS (Optional)</topic>
		</detailed-topics>
		<other-imp-details>
			<student-profiles>
				<profile>Professionals working in software, who want to change their stream to Java </profile>
				<profile>Fresh/Recent graduates looking for a job in software</profile>
				<profile>Students still in college looking to prepare for the software career and campus placement.</profile>
			</student-profiles>
			<placement-features>
				<feature>Placement guidance</feature>
				<feature>Placement-focussed quizzes</feature>
				<feature>Mock Interviews</feature>
				<feature>Personalized 1:1 feedback and mentoring</feature>
				<feature>Placement-focussed quizzes</feature>
				<feature>Mock Interviews</feature>
			</placement-features>
		</other-imp-details>
		<trainer>
			<name>Manas Panda</name>
			<description>
				Manas has more than 10 years of experience in software development and has worked with top companies like Wipro, Oracle, EMC &amp; Intuit. He has developed and led many project in both *Server Side programming* _(Java, Spring, Hibernate, SQL etc)_ and *front-end development* (Android, HTML/CSS/JQuery/AngularJS). 
 				
				He is highly passionate about teaching programming to the beginners in the _right way_.
			</description>
		</trainer>
		<faqs>
			<faq>
				<question>Where will be the classroom sections conducted?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What are the projects I will be doing?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What is the refund policy?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>How is this program different from other classroom programs?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>Is any pre-knowledge required to take this course?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What do I bring to the class? Anything I need to buy?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What do I get at the end of the course?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>When are the exams?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
		</faqs>
		<course-outline>
			
		</course-outline>
		
	</course>
	
	<course>
		<course-name>CoreJava</course-name>
		<short-description>Core Java for Beginners</short-description>
		<duration>2 Months (60 Days)</duration>
		<start-date>25 Nov 2016</start-date>
		<coursefee>11,000</coursefee>
		<classroom-location>Marathahalli, Bangalore</classroom-location>
		<placement-support-available>Y</placement-support-available>
		<clickthrough-to-details>Y</clickthrough-to-details>
		<long-description>Our innovative courses are designed to help students, fresh/recent graduates get a software job by building pro. Our innovative courses are designed to help students, fresh/recent graduates get a software job by building pro.</long-description>
		<pre-registration-allowed>N</pre-registration-allowed>
		<early-registration-fee></early-registration-fee>
		<tags>
			<tag>Placement Focussed</tag>
			<tag>Beginner Level</tag>
			<tag>Mentor Guidance</tag>
		</tags>
		<what-it-includes>
			<core>Core Java, SQL, JDBC</core>
			<optional>None</optional>
			<others>5 Foundation projects + 2 Major projects</others>
			<others>Assignment, Quizzes, Group work &amp; Reviews</others>
			<others>1:1 Mentoring &amp; Doubt Clearing Sessions</others>	
			<others>6 Month access to online discussion and help forum</others>				
		</what-it-includes>
		<detailed-topics>
			<topic>Core Java</topic>
			<topic>SQL &amp; JDBC</topic>
			<topic>Data Structure &amp; Algorithm (Optional)</topic>
		</detailed-topics>
		<other-imp-details>
			<student-profiles>
				<profile>Professionals working in software, who want to change their stream to Java </profile>
				<profile>Fresh/Recent graduates looking for a job in software</profile>
				<profile>Students still in college looking to prepare for the software career and campus placement.</profile>
			</student-profiles>
			<placement-features>
				<feature>Placement guidance</feature>
				<feature>Placement-focussed quizzes</feature>
				<feature>Mock Interviews</feature>
				<feature>Personalized 1:1 feedback and mentoring</feature>
				<feature>Placement-focussed quizzes</feature>
				<feature>Mock Interviews</feature>
			</placement-features>
		</other-imp-details>
		<trainer>
			<name>Manas Panda</name>
			<description>
				Manas has more than 10 years of experience in software development and has worked with top companies like Wipro, Oracle, EMC &amp; Intuit. He has developed and led many project in both *Server Side programming* _(Java, Spring, Hibernate, SQL etc)_ and *front-end development* (Android, HTML/CSS/JQuery/AngularJS). 
 				
				He is highly passionate about teaching programming to the beginners in the _right way_.
			</description>
		</trainer>
		<faqs>
			<faq>
				<question>Where will be the classroom sections conducted?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What are the projects I will be doing?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What is the refund policy?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>How is this program different from other classroom programs?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>Is any pre-knowledge required to take this course?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What do I bring to the class? Anything I need to buy?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>What do I get at the end of the course?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
			<faq>
				<question>When are the exams?</question>
				<answer>We have several classrooms around the city. Based on student enrollments and convenience, we decide the right classroom for the batch.</answer>
			</faq>
		</faqs>
		<course-outline>
			
		</course-outline>
		
	</course>
	
	
	<course>
		<course-name>Android</course-name>
		<short-description>Android Programming for Beginners</short-description>
		<duration>2 Months (60 Days)</duration>
